// Generated by cbindgen. Do not edit by hand.

#ifndef FLORESTA_FFI_H
#define FLORESTA_FFI_H

#pragma once

/* This file is autogenerated. Edits will be overwritten. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct FlorestaNode FlorestaNode;

/**
 * Runtime tuning knobs forwarded to `UtreexoNodeConfig`. Pass NULL to
 * `floresta_node_new` to use the mobile-friendly defaults below.
 */
typedef struct FlorestaConfig {
  /**
   * Enable assumeutreexo with the network's hardcoded snapshot — fast sync
   * at the cost of trusting the snapshot baked into the fork.
   */
  bool assume_utreexo;
  /**
   * When assumeutreexo is on, also download and verify historical blocks in
   * the background to upgrade from "trusted" to "fully validated".
   */
  bool backfill;
  /**
   * Use PoW fraud proofs to skip most of the chain validation. Off by
   * default — exclusive with `assume_utreexo` in practice.
   */
  bool pow_fraud_proofs;
  /**
   * Skip DNS seeds. Useful for tests; in production we want them on.
   */
  bool disable_dns_seeds;
  /**
   * Allow falling back to P2P v1 if the v2 handshake fails.
   */
  bool allow_v1_fallback;
  /**
   * Peer misbehaviour threshold before disconnecting. Floresta default is 100.
   */
  uint32_t max_banscore;
} FlorestaConfig;

typedef struct FlorestaSyncStatus {
  uint32_t height;
  uint32_t headers;
  uint32_t peers;
  bool in_ibd;
  double progress;
} FlorestaSyncStatus;

char *floresta_ffi_version(void);

void floresta_ffi_string_free(char *ptr);

struct FlorestaNode *floresta_node_new(const char *data_dir,
                                       uint32_t network,
                                       const struct FlorestaConfig *config);

bool floresta_node_start(struct FlorestaNode *node);

void floresta_node_stop(struct FlorestaNode *node);

struct FlorestaSyncStatus floresta_node_status(struct FlorestaNode *node);

void floresta_node_free(struct FlorestaNode *node);

#endif  /* FLORESTA_FFI_H */
